# Data structure in Python

# Lists

In [4]:
#Lists combination of elements
# Ex: x=[1,'r',100]

In [39]:
x=[1,'R','Python',100]
x[0]
x[-2]
x[3]
x[0:3]
x.append(['New','List'])
x

[1, 'R', 'Python', 100, ['New', 'List']]

In [21]:
x=[1,9,['R','Python',['GL','Data'],2],1]
x[2][1]
x[2][2][1]
x[-2][-2][-1]
x[-2][-3]

'Python'

# Dictionaries 

In [35]:
#Dictionaries are unordered datatype they donot support indexing
#They are key value pair
#Keys must be immutable cannot be changes once assigned
#tuples
d={'k1':3,'k2':5,1:2}
d1={'k1':'v1','k2':'v2'}
type(d)
d.keys()
d.values()
d[1]    #d[Key]
dicti={1:[1,2],2:3}
dicti[1][1]

2

# Tuples

In [42]:
#Tuples is a sequence or ordered of immutable python objet.Tuples are sequences,
#just like list. The differences between tuple and lists are 
#Cannot be changed unlike lists and tuples use parentheses, where list use square bracket

t=(1,2)
t[0]
#x[0]=5    ---gives an error

1

# Sets

In [43]:
#Set is unordered, immutable datatype , it is iterable and has no duplicate elements
#Python set is a notation of mathematical stes
s={1,2,5,1,11}
s

{1, 2, 5, 11}

# Loops in python

In [62]:
#x=[1,2,3]*3 #Repeats same lis thrice
#Broadcasting is acessinging induvidual element and perform some operation , as whole no opersations can be performed
x1=[1,2,3]
#####For loop
for i in x1:
    print (i*2)

2
4
6


In [55]:
###While loop
i = 5
while i<10:
    print (i)
    if(i<8):
        print (i)
    i=i+1

5
5
6
6
7
7
8
9


In [66]:
x2=[1,2,3]
i=0
while i<len(x2):
    if(x2[i]%2==0):
        print("Even")
    else:
        print("odd")
    i=i+1

    

odd
Even
odd


In [72]:
x1=[12,20,30]
for n in x1:
    if(n%2==0):
        print("Even")
    else:
        print("odd")

Even
Even
Even


In [80]:
import math
num=7
sqr=math.sqrt(num)
i=2
while(i<=sqr):
    if(num%i!=0):
        print("Prime")
    i=i+1

Prime


In [120]:
import math
numlist=[5,7,12,15,23,3,2,1,6]
for i in numlist:
    n=range(2,int(np.ceil(math.sqrt(i))))
    flag=True
    for j in n:
            if(i%j==0):
                flag=False
    if(flag):
        print("Prime")
    else:
        print("Not prime")
        

Prime
Prime
Not prime
Not prime
Prime
Prime
Prime
Prime
Not prime


# Loading Numpy

In [107]:
import numpy as np

# Comprehension in python

In [122]:
alist=[1,2,3,4]
[i*2 for i in alist]

[2, 4, 6, 8]

In [136]:
word='The quick brown fox jumps over the lazy dog'.split()
f=[[i.upper(),i.lower(),len(i)] for i in word]
print(f)

[['THE', 'the', 3], ['QUICK', 'quick', 5], ['BROWN', 'brown', 5], ['FOX', 'fox', 3], ['JUMPS', 'jumps', 5], ['OVER', 'over', 4], ['THE', 'the', 3], ['LAZY', 'lazy', 4], ['DOG', 'dog', 3]]


In [137]:
[i for i in range(1,20) if i%2==0]

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [138]:
[(x,y,z) for x in range(1,30) for y in range(x,30) for z in range(y,30)if x**2+y**2==z**2]

[(3, 4, 5),
 (5, 12, 13),
 (6, 8, 10),
 (7, 24, 25),
 (8, 15, 17),
 (9, 12, 15),
 (10, 24, 26),
 (12, 16, 20),
 (15, 20, 25),
 (20, 21, 29)]

In [139]:
####Intersection of 2 lis
x=[1,2,3]
y=[2,3,4,5]
[i for i in x if i in y]

[2, 3]

In [141]:
##A-B of list
[i for i in x if i not in y]
##B-A in list
[i for i in y if i not in x]

[4, 5]

In [143]:
['odd' for i in x if i%2!=0 ]

['odd', 'odd']

In [154]:
['odd' if  i%2!=0 else 'even' for i in x]

['odd', 'even', 'odd']

# Array

In [164]:
ar=range(50)
ar=np.array(ar).reshape(5,10)
print(ar)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [182]:
print(ar[0,[1,3]])
print(ar[0,4])
print(ar[1,3:])
[ar[4,i] for i in [0,2,3]]

[1 3]
4
[13 14 15 16 17 18 19]


[40, 42, 43]

In [194]:
print(ar[(ar>20) & (ar<30)])

[21 22 23 24 25 26 27 28 29]


In [195]:
ar.shape

(5, 10)

In [200]:
np.random.rand(10) #uniform distribution
np.random.randn(10)#Normal distribution
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

# Series 

In [219]:
#Series
import pandas as pd
label=["A","B","C","D"]
dta=[10,20,30,40]
arr=np.array(dta)
type(label),type(dta),type(arr)

(list, list, numpy.ndarray)

In [228]:
aseries=pd.Series(data=dta,index=label)
aseries

A    10
B    20
C    30
D    40
dtype: int64

# Dataframes

In [230]:
df=pd.DataFrame(data=arr.reshape(2,2),columns=[['one','two']],index=['one','two'])
df


one two
one  10  20
two  30  40

# Readingcsv

In [245]:
Boston_df=pd.read_csv("/Users/rsklanu/Pythonday1/Boston.csv")

Boston_df=Boston_df.drop("Unnamed: 0",axis=1)
Boston_df.head()
Boston_df["medv"]>30
np.sum(Boston_df["medv"]>30)
Boston_df.info()
Boston_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
crim       506 non-null float64
zn         506 non-null float64
indus      506 non-null float64
chas       506 non-null int64
nox        506 non-null float64
rm         506 non-null float64
age        506 non-null float64
dis        506 non-null float64
rad        506 non-null int64
tax        506 non-null int64
ptratio    506 non-null float64
black      506 non-null float64
lstat      506 non-null float64
medv       506 non-null float64
dtypes: float64(11), int64(3)
memory usage: 55.4 KB


crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677082   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio       black  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat        medv  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [253]:
Boston_df[(Boston_df["medv"]==np.max(Boston_df["medv"])) & (Boston_df["chas"]==1)]
Boston_df[(Boston_df["medv"]==np.max(Boston_df["medv"]))]

crim    zn  indus  chas     nox     rm    age     dis  rad  tax  \
161  1.46336   0.0  19.58     0  0.6050  7.489   90.8  1.9709    5  403   
162  1.83377   0.0  19.58     1  0.6050  7.802   98.2  2.0407    5  403   
163  1.51902   0.0  19.58     1  0.6050  8.375   93.9  2.1620    5  403   
166  2.01019   0.0  19.58     0  0.6050  7.929   96.2  2.0459    5  403   
186  0.05602   0.0   2.46     0  0.4880  7.831   53.6  3.1992    3  193   
195  0.01381  80.0   0.46     0  0.4220  7.875   32.0  5.6484    4  255   
204  0.02009  95.0   2.68     0  0.4161  8.034   31.9  5.1180    4  224   
225  0.52693   0.0   6.20     0  0.5040  8.725   83.0  2.8944    8  307   
257  0.61154  20.0   3.97     0  0.6470  8.704   86.9  1.8010    5  264   
267  0.57834  20.0   3.97     0  0.5750  8.297   67.0  2.4216    5  264   
283  0.01501  90.0   1.21     1  0.4010  7.923   24.8  5.8850    1  198   
368  4.89822   0.0  18.10     0  0.6310  4.970  100.0  1.3325   24  666   
369  5.66998   0.0  18.10     1  0.6310  6.683   96.8  1.3567   24  666   
370  6.53876   0.0  18.10     1  0.6310  7.016   97.5  1.2024   24  666   
371  9.23230   0.0  18.10     0  0.6310  6.216  100.0  1.1691   24  666   
372  8.26725   0.0  18.10     1  0.6680  5.875   89.6  1.1296   24  666   

     ptratio   black  lstat  medv  
161     14.7  374.43   1.73  50.0  
162     14.7  389.61   1.92  50.0  
163     14.7  388.45   3.32  50.0  
166     14.7  369.30   3.70  50.0  
186     17.8  392.63   4.45  50.0  
195     14.4  394.23   2.97  50.0  
204     14.7  390.55   2.88  50.0  
225     17.4  382.00   4.63  50.0  
257     13.0  389.70   5.12  50.0  
267     13.0  384.54   7.44  50.0  
283     13.6  395.52   3.16  50.0  
368     20.2  375.52   3.26  50.0  
369     20.2  375.33   3.73  50.0  
370     20.2  392.05   2.96  50.0  
371     20.2  366.15   9.53  50.0  
372     20.2  347.88   8.88  50.0

In [263]:
Boston_df.loc[195,"lstat"]
Boston_df.iloc[:5]
Boston_df.iloc[2,5]
Boston_df.iloc[1:15,-2:]

lstat  medv
1    9.14  21.6
2    4.03  34.7
3    2.94  33.4
4    5.33  36.2
5    5.21  28.7
6   12.43  22.9
7   19.15  27.1
8   29.93  16.5
9   17.10  18.9
10  20.45  15.0
11  13.27  18.9
12  15.71  21.7
13   8.26  20.4
14  10.26  18.2

# Missing Value

In [277]:
df=({'A':[1,2,np.nan],
    'B':[5,np.nan,np.nan],
    'C':[1,2,3]})
df=pd.DataFrame(df)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [278]:
df.dropna(axis=0)

A    B  C
0  1.0  5.0  1

In [279]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [280]:
df.dropna(thresh=2,axis=0)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [281]:
df.fillna(value="FNa")

A    B  C
0    1    5  1
1    2  FNa  2
2  FNa  FNa  3

In [286]:
df['B'].fillna(value=df['B'].mean()) #,inplace=True)
df['A'].fillna(value=df['A'].mean()) #,inplace=True)
df.isnull().sum()
df.isna().sum()

A    1
B    2
C    0
dtype: int64

In [ ]:
dat={'Company':['Goog','Goog','MSFT','MSFT','bla']}

In [289]:
#df.groupby('company')['Sales'].mean()
#Merging, Joining and concatenantion
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                 'B':['B0','B1','B2','B3'],
                 'C':['C0','C1','C2','C3'],
                 'D':['D0','D1','D2','D3']},index=[0,1,2,3])
df1

df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                 'B':['B4','B5','B6','B7'],
                 'C':['C4','C5','C6','C7'],
                 'D':['D4','D5','D6','D7']},index=[0,1,2,3])
df2

A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [291]:
pd.merge(df1,df2,how="outer",on="D")

A_x  B_x  C_x   D  A_y  B_y  C_y
0   A0   B0   C0  D0  NaN  NaN  NaN
1   A1   B1   C1  D1  NaN  NaN  NaN
2   A2   B2   C2  D2  NaN  NaN  NaN
3   A3   B3   C3  D3  NaN  NaN  NaN
4  NaN  NaN  NaN  D4   A4   B4   C4
5  NaN  NaN  NaN  D5   A5   B5   C5
6  NaN  NaN  NaN  D6   A6   B6   C6
7  NaN  NaN  NaN  D7   A7   B7   C7

In [296]:
pd.concat([df1,df2],axis=0,ignore_index=True)
#pd.concat([df1,df2],axis=1,ignore_index=True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [299]:
##table in R for confusion matrix df1['A'].value_counts()
df1['A'].value_counts()

A2    1
A0    1
A1    1
A3    1
Name: A, dtype: int64